### PR TITLE
Table Rendered docs

### PR DESCRIPTION
**Pull request by kevinbird15**
Here is the code I changed up to make the table version of the docs.  Let me know if you want to discuss or don't like anything that I changed.

### CODE REVIEW

**Comment by muellerzr** [comment]
Nice job with this! As mentioned on discord, I think we can clean this up quite a bit. Let's add something like this:

```python
_TABLE_CSS = """<style>
    table { border-collapse: collapse; border:thin solid #dddddd; margin: 25px 0px; ; }
    table tr:first-child { background-color: #FFF}
    table thead th { background-color: #eee; color: #000; text-align: center;}
    tr, th, td { border: 1px solid #ccc; border-width: 1px 0 0 1px; border-collapse: collapse;
    padding: 5px; }
    tr:nth-child(even) {background: #eee;}</style>"""
```
And then in `doc()`:
```python
    else:
        try: page.page({'text/html': output + _TABLE_CSS})
        except: display(Markdown(md))
```

This gives us a pretty close rendering to that of `show_doc` as a pop-out in Jupyter

**Comment by kevinbird15** [comment]
added.  I did use `display(HTML(output + _TABLE_CSS))` rather than Markdown for the except, but let me know if you don't like it and I'll swap back.

**Comment by muellerzr** [comment]
Let's keep it back to the `Markdown` :) 

**Big** importance here: We are *only* changing the `text/html` to need the formatting. the `except` has no need for the formatting, this is why we do not do so.

**Comment by kevinbird15** [comment]
Should we do anything to the colab `output`?  Does it make sense to add your custom css there as well?

**Comment by muellerzr** [comment]
Yup, `in_colab` should have it too. Nice catch:

```python
    if IN_COLAB: get_ipython().run_cell_magic(u'html', u'', output + _TABLE_CSS)
    else:
        try: page.page({'text/html': output + _TABLE_CSS})
        except: display(Markdown(output))
```

**Comment by kevinbird15** [comment]
Ok, I believe all changes have been made now

**Comment by muellerzr** [comment]
One more little bit and we should be fine.

Currently we still show the table for returns even if there is no return documentation provided. We should not do so if there is no documentation (currently `nbverbose` has a conditional for that). 
image

So we should keep the existing behavior in that way :) 

Also `show_doc` needs the `in_colab` treatment as well

**Pull request merged**
